### ISSUE TITLE
[QA] autoprovisioning does not import the fullname 

### ISSUE THREAD

**Issue by jnweiger** [owncloud/openidconnect#139] opened 2021-01-26 13:53 UTC
Tested with openidconnect-2.0.0RC1 on oc-10.6.0 with php-7.4.3 connected against Azure AD

My Test user at Azure AD is named "Juergen Weigert"
With autoprovisioning on, the user gets created in ownCloud as oidc-user-60100f71354ec

Expected behaviour: The user would also show up as Full name 'Juergen Weigert' in owncloud.

![image](https://user-images.githubusercontent.com/1108546/105853182-b1332280-5fe5-11eb-8a8c-8ada032200ce.png)

**Comment by jnweiger** [comment] 2021-01-26 13:57
Confguration used:

```
  array (
    'provider-url' => 'https://login.microsoftonline.com/CCCCCCCCCCCCCCCCCCCC/v2.0',
    'client-id' => 'BBBBBBBBBBBBBBBB',
    'client-secret' => 'AAAAAAAAA',
    'loginButtonName' => 'Azure AD (OIDC)',
    'scopes' =>
    array (
          'openid', 'api://NNNNNNNNNNNNNNNNNNNNNNN/owncloud', 'profile', 'email', 'offline_access'
    ),
    'auto-provision' => [
        // explicit enable the auto provisioning mode
        'enabled' => true,
        // documentation about standard claims: https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims
        // only relevant in userid mode,  defines the claim which holds the email of the user
        'email-claim' => 'email',
        // defines the claim which holds the display name of the user
        'display-name-claim' => 'given_name',
        // defines a list of groups to which the newly created user will be added automatically
        'groups' => ['admin', 'guests', 'employees'],
      ],
    'mode' => 'email',
    'autoRedirectOnLoginPage' => false,
    'search-attribute' => 'unique_name',
    'use-access-token-payload-for-user-info' => true,
    'redirect-url' => 'https://oc-10-6-0XXXXXXX.jw-qa.XXXXXX/index.php/apps/openidconnect/redirect',
  ),
```

**Comment by DeepDiver1975** [comment] 2021-04-29 10:04
You also need to verify that the user info (in case of Azure this is within the access token which is a JWT) actually holds a claim named 'fullname'.
If named different -> change config
If claim is missing -> change Azure config

**Comment by DeepDiver1975** [comment] 2021-04-29 10:04
closing for now - not a bug

**Closed by DeepDiver1975** 2021-04-29 10:04 UTC

**Comment by mmattel** [comment] 2021-04-29 10:37
need to ask, ist this something that could be supported/clarified via a docs improvement?
(beside reading the oidc specs of course ...)

**Comment by DeepDiver1975** [comment] 2021-04-29 12:21
> need to ask, ist this something that could be supported/clarified via a docs improvement?
> (beside reading the oidc specs of course ...)

not from my understanding - somebody configuring openid connect should understand basic concepts.
it is clear what a claim is claim is and this is straight forward.

to me this is like: shall we explain that 1 + 1 = 2? - No - get a Math book and read things up there ;-)
